const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      gridTemplateRows: {
        // Simple 8 row grid
        '8': 'repeat(8, minmax(0, 1fr))',
        '9': 'repeat(9, minmax(0, 1fr))',
        '10': 'repeat(10, minmax(0, 1fr))',
        '11': 'repeat(11, minmax(0, 1fr))',
        '12': 'repeat(12, minmax(0, 1fr))',
      },
      gridRow: {
        'span-7': 'span 7 / span 7',
        'span-8': 'span 8 / span 8',
        'span-9': 'span 9 / span 9',
        'span-10': 'span 10 / span 10',
        'span-11': 'span 11 / span 11',
        'span-12': 'span 12 / span 12',
      },
      backgroundImage: {
        "datadisruptor": "url('/AVLogicEditorJS/imgs/DataDisruptor.svg')",
        "nova": "url('/AVLogicEditorJS/imgs/Nova.svg')",
        "sizenode": "url('/AVLogicEditorJS/imgs/SizeNode.svg')",
        "drill": "url('/AVLogicEditorJS/imgs/Drill.svg')",
        "powernode": "url('/AVLogicEditorJS/imgs/PowerNode.svg')",
        "multidisruptor": "url('/AVLogicEditorJS/imgs/MultiDisruptor.svg')",
        "healthnode": "url('/AVLogicEditorJS/imgs/HealthNode.svg')",
        "healthnodefragment": "url('/AVLogicEditorJS/imgs/HealthNodeFragment.svg')",
        "kilver": "url('/AVLogicEditorJS/imgs/Kilver.svg')",
        "addressdisruptor1": "url('/AVLogicEditorJS/imgs/AddressDisruptor1.svg')",
        "addressdisruptor2": "url('/AVLogicEditorJS/imgs/AddressDisruptor2.svg')",
        "powernodefragment": "url('/AVLogicEditorJS/imgs/PowerNodeFragment.svg')",
        "note": "url('/AVLogicEditorJS/imgs/Note.svg')",
        "highjump": "url('/AVLogicEditorJS/imgs/HighJump.svg')",
        "firewall": "url('/AVLogicEditorJS/imgs/FireWall.svg')",
        "glitchteleport": "url('/AVLogicEditorJS/imgs/GlitchTeleport.svg')",
        "rangenode": "url('/AVLogicEditorJS/imgs/RangeNode.svg')",
        "tendrilstop": "url('/AVLogicEditorJS/imgs/TendrilsTop.svg')",
        "dronegun": "url('/AVLogicEditorJS/imgs/DroneGun.svg')",
        "passwordtool": "url('/AVLogicEditorJS/imgs/PasswordTool.svg')",
        "voranj": "url('/AVLogicEditorJS/imgs/Voranj.svg')",
        "verticalspread": "url('/AVLogicEditorJS/imgs/VerticalSpread.svg')",
        "inertialpulse": "url('/AVLogicEditorJS/imgs/InertialPulse.svg')",
        "grapple": "url('/AVLogicEditorJS/imgs/Grapple.svg')",
        "tetheredcharge": "url('/AVLogicEditorJS/imgs/TetheredCharge.svg')",
        "reflect": "url('/AVLogicEditorJS/imgs/Reflect.svg')",
        "enhancedlaunch": "url('/AVLogicEditorJS/imgs/EnhancedLaunch.svg')",
        "blackcoat": "url('/AVLogicEditorJS/imgs/BlackCoat.svg')",
        "glitchbomb": "url('/AVLogicEditorJS/imgs/GlitchBomb.svg')",
        "lightninggun": "url('/AVLogicEditorJS/imgs/LightningGun.svg')",
        "shards": "url('/AVLogicEditorJS/imgs/Shards.svg')",
        "droneteleport": "url('/AVLogicEditorJS/imgs/DroneTeleport.svg')",
        "distortionfield": "url('/AVLogicEditorJS/imgs/DistortionField.svg')",
        "datagrenade": "url('/AVLogicEditorJS/imgs/DataGrenade.svg')",
        "tricone": "url('/AVLogicEditorJS/imgs/TriCone.svg')",
        "tendrilsbottom": "url('/AVLogicEditorJS/imgs/TendrilsBottom.svg')",
        "breachsuppressor": "url('/AVLogicEditorJS/imgs/BreachSuppressor.svg')",
        "redcoat": "url('/AVLogicEditorJS/imgs/RedCoat.svg')",
        "ionbeam": "url('/AVLogicEditorJS/imgs/IonBeam.svg')",
        "scythe": "url('/AVLogicEditorJS/imgs/Scythe.svg')",
        "walltrace": "url('/AVLogicEditorJS/imgs/WallTrace.svg')",
        "flamethrower": "url('/AVLogicEditorJS/imgs/FlameThrower.svg')",
        "swim": "url('/AVLogicEditorJS/imgs/Swim.svg')",
        "fatbeam": "url('/AVLogicEditorJS/imgs/FatBeam.svg')",
        "heatseeker": "url('/AVLogicEditorJS/imgs/HeatSeeker.svg')",
        "webslicer": "url('/AVLogicEditorJS/imgs/WebSlicer.svg')"
      }
    }
  },
  variants: {
    textFillColor: ['responsive'],
    extends: {
      backgroundColor: ['checked', 'first', 'last', 'even', 'odd'],
      padding: ['responsive', 'first', 'last'],
      margin: ['responsive', 'first', 'last'],
    },
  },
  plugins: [],
}
