import { useState, useEffect } from 'react';
import Head from 'next/head';
import Header from 'components/Header';
import { MainContainer, SecondaryContainer } from 'components/Containers';
import { PlusIcon, MinusIcon } from "@heroicons/react/24/solid";
import { classNames } from 'utils';
import HeaderButton from 'components/HeaderButton';

// Simulated Power Flags
const Powers = {
  None: 0,
  Gun: 1 << 0,
  Nova: 1 << 1,
  Drill: 1 << 2,
  Kilver: 1 << 3,
  AddressDisruptor1: 1 << 4,
  HighJump: 1 << 5,
  Labcoat: 1 << 6,
  Drone: 1 << 7,
  AddressDisruptor2: 1 << 8,
  Grapple: 1 << 9,
  Trenchcoat: 1 << 10,
  AddressBombs: 1 << 11,
  DroneTeleport: 1 << 12,
  ExtendedDroneLaunch: 1 << 13,
  SudranKey: 1 << 14,
  RedCoat: 1 << 15,
  Password: 1 << 16,
  LongKilver: 1 << 17,
  FatBeam: 1 << 18,
  TeleReset: 1 << 19,

  // Helper functions
  hasPower(powers, power) {
    return (powers & power) === power;
  },

  addPower(powers, power) {
    return powers | power;
  },

  removePower(powers, power) {
    return powers & ~power;
  }
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Axiom Verge Randomizer Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-full bg-gray-100 overflow-hidden">
        <MainContainer>
          <Header title="Axiom Verge Randomizer Tools" version="0.0.1">
            <div className="w-1/8 h-full flex gap-2 justify-center items-center">
              <HeaderButton title="Items" url="/items" active={false} />
              <HeaderButton title="Locations" url="/locations" active={false} />
              <HeaderButton title="Tracker" url="/map/tracker" active={false} />
              <HeaderButton title="Debugger" url="/map/debugger" active={false} />
            </div>
          </Header>
          <div className="bg-gray-900 w-full h-full flex flex-col justify-center items-center text-gray-200 font-bold">
            <img className="w-1/2" src="imgs/TitleScreen.png" />
            <h1>Welcome to the AVR Web Tool Kit</h1>
            <p>Developed By VideoGameRoulette</p>
          </div>
        </MainContainer>
      </div>
    </>
  )
}
