import Head from 'next/head';
import Header from 'components/Header';
import { MainContainer } from 'components/Containers';
import HeaderButton from 'components/HeaderButton';

export default function Home() {
  return (
    <>
      <Head>
        <title>Axiom Verge Randomizer Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-full bg-gray-100 overflow-hidden">
        <MainContainer>
          <Header title="Axiom Verge Randomizer Tools" version="0.0.1">
            <div className="w-1/8 h-full flex gap-2 justify-center items-center">
              <HeaderButton title="Items" url="/items" active={false} />
              <HeaderButton title="Locations" url="/locations" active={false} />
              <HeaderButton title="Tracker" url="/map/tracker" active={false} />
              <HeaderButton title="Debugger" url="/map/debugger" active={false} />
            </div>
          </Header>
          <div className="bg-gray-900 w-full h-full flex flex-col justify-center items-center text-gray-200 font-bold">
            <img className="w-1/2" src="imgs/TitleScreen.png" />
            <h1>Welcome to the AVR Web Tool Kit</h1>
            <p>Developed By VideoGameRoulette</p>
          </div>
        </MainContainer>
      </div>
    </>
  )
}
